[package]
name = "trace-anal"
version = "0.1.0"
authors = ["Kitsu <mail@kitsu.me>"]

[dependencies]
simple_json = "0.2.3"
itertools = "0.7.4"
dot = { git = "https://github.com/l4l/dot-rust.git", branch = "develop" }
